### ISSUE TITLE
Invalid attribute name error

### ISSUE THREAD

**Issue by charmpitz** [sindresorhus/grunt-svgmin#15]
Warning: Error parsing SVG: Invalid attribute name Use --force to continue.

Hey this is the error i get. First time i ran grunt it worked like a charm and made the optimisations but after that i keep getting this. This is my configuration:

svgmin: {
    options: { 
        plugins: [
          { removeViewBox: false },
          { removeUselessStrokeAndFill: false }
        ]
    },
    dist: {
        files: [{
            expand: true,
            cwd: 'static-html/assets/',
            src: ['*_/_.svg'],
            dest: 'static-html/assets/',
            ext: '.svg'
        }]
    }
}

**Comment by techjwalker** [comment]
I know this issue is old and closed, but I thought it was too funny not to mention.

Apparently @sindresorhus pushes these issue to SVGO, meanwhile SVGO tends to close these issues "because grunt" essentially.

And thus the cycle continues, I guess.
