### ISSUE TITLE
Pretty Print

### ISSUE THREAD

**Issue by alex-martinez** [sindresorhus/grunt-svgmin#32]
Can I pretty print from this plugin? I know I can with SVGO, but is it possible through Grunt?

My goal is to create a defs.svg file with grunt-svgstore, then pretty print it with SVGO.

**Comment by sindresorhus** [comment]
No

**Comment by VodkaBears** [comment]
Yes.
```js
options: {
  js2svg: {
    pretty: true
  }
}
```

**Comment by Crissov** [comment]
I guessed the same as @vodkabears but it does not work for me, neither in `options` nor in `default`:

```
	svgmin: {
		options: {
			pretty: true,
			plugins: [/*...*/]
		},
		default: {
			pretty: true,
			files:  [{
				expand: true,
				cwd: 'svg',
				src: '*.svg',
				dest: 'svg'
			}]
		}
	}
```

This really should just work. Can you please reopen the issue and implement/document the option, @sindresorhus?
