### ISSUE TITLE
Target-specific configurations do not work

### ISSUE THREAD

**Issue by micropat** [sindresorhus/grunt-svgmin#37]
```javascript
svgmin: {
  // Arbitrarily named target
  foo: {
    dist: {
        files: {'dist/svg.svg': 'src/svg.svg'}
      }
    }
}
```

Running "svgmin:foo" (svgmin) task
Verifying property svgmin.foo exists in config...OK
File: [no files]
Options: (none)
Total saved: 0 B

**Comment by sindresorhus** [comment]
That confit is invalid. You have one too many nestings.

**Comment by micropat** [comment]
The plugin doesn't support [multiple configurations](http://gruntjs.com/configuring-tasks#task-configuration-and-targets).
