### ISSUE TITLE
Option to hide logging

### ISSUE THREAD

**Issue by bluetidepro** [sindresorhus/grunt-svgmin#42]
It would be really nice if there was an option to hide all the grunt logging statements to git rid of some of the clutter in the console.

Maybe add an option wrapping around https://github.com/sindresorhus/grunt-svgmin/blob/master/tasks/svgmin.js#L29 to either show or hide those log statements?

**Comment by sindresorhus** [comment]
That should be fixed in grunt by adding log levels. I'm not interested in having log related options in this task. You could always `$ grunt &>/dev/null`

https://github.com/ericclemmons/grunt-verbosity
https://github.com/bahmutov/quiet-grunt

**Comment by bluetidepro** [comment]
@sindresorhus What about only wrapping it in verbose, so it shows up there and I don't have to introduce more libraries to hide it?

**Comment by sindresorhus** [comment]
I tried that on some other plugins and people complained about the files not being shown in the output. I'm done changing back and forth. People will complain either way.
