### ISSUE TITLE
filename with errors, parse & encode problem characters?

### ISSUE THREAD

**Issue by v3nt** [sindresorhus/grunt-svgmin#46]
When working with 20 or more files it would really halve if svgmin could tell us what file has the issue. Even a line number if possible!

Warning: Error parsing SVG: FILENAME.svg : line :12

Its mostly getting stuck on SVGs from illustrator. Is there a way it could correct the issues before processing it and failing due to errors. The biggest issue seems to be & but when converted to &amp; it works fine.

<img width="598" alt="screen shot 2016-01-08 at 14 46 45" src="https://cloud.githubusercontent.com/assets/6348562/12200439/c4699916-b616-11e5-977e-b92f1599f9bd.png">

**Comment by sindresorhus** [comment]
Added filename to errors. As for line number, that needs to be fixed upstream: https://github.com/svg/svgo/issues/482
