### ISSUE TITLE
Removes the svg tag ID

### ISSUE THREAD

**Issue by ecker00** [sindresorhus/grunt-svgmin#56]
Not sure if it's a feature or a bug, but even with the "removeAttrs" option disabled it still remove the ID from the <svg> tag. This ID is needed when loading external SVGs inside other SVGs with the <use> tag.

Also wondering if there is a way to disable the ID renaming of the child elements?

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the SVGO [issue tracker](https://github.com/svg/svgo/issues).*

---

Most likely you'll need to disable it in the options.

**Comment by ecker00** [comment]
Cheers, found what I was looking for! :)
Sorry for the mistake.
