### ISSUE TITLE
Is there a way to support multiple files?

### ISSUE THREAD

**Issue by mtsweir** [sindresorhus/grunt-svgmin#65]
This is my grunt task setup:

```
module.exports = {
	 options: {
		plugins: [
			{ cleanupIDs: false },
			{ removeEmptyAttrs: false},
			{ removeUselessStrokeAndFill: false},
			{ removeViewBox: false },
			{
				removeAttrs: {
					attrs: [
						'xmlns'
					]
				}
			}
		]
	},
	dist: {
		files: {
			'defs.svg': 'src/svg/*.svg'
		}
	}
}
```

But when I run the grunt process it only processes the first file in the directory.

Also, is there a way to stop the minification? my defs file looks like this after processing:
```
<svg width="20" height="20" viewBox="0 0 20 20"><path d="M4 4l12 12M4 16L16 4" id="cancel" stroke="currentcolor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>
```

But would like to see this separated line by line when developing so its easier to read and ensure the output is as I need it to be.

**Comment by velPL** [comment]
You may use the following syntax to process multiple files:
`			dist: {
				files: [{               
					expand: true,       
					cwd: '/assets/sources/svg',     
					src: ['*.svg'],  
					dest: 'dist/svg',
					ext: '.min.svg'     
				}]	
			}	`

**Comment by mtsweir** [comment]
@velPL thanks, is it also possible to process multiple directories?

I have two SVG folders that I need to process separately and the "dest" is a different folder as well.

So I'm trying to process this:

**cwd:**
/src/svg/icons
/src/svg/pictograms

**dest:**
/src/svg/min/icons
/src/svg/min/pictograms

**Comment by velPL** [comment]
I believe you should try something like:
```
			icons: {
				files: [{               
					expand: true,       
					cwd: '/src/svg/icons',     
					src: ['*.svg'],  
					dest: '/src/svg/min/icons,
					ext: '.min.svg'     
				}]	
			},
			pictograms: {
				files: [{               
					expand: true,       
					cwd: '/src/svg/pictograms',     
					src: ['*.svg'],  
					dest: '/src/svg/min/pictograms,
					ext: '.min.svg'     
				}]	
			}

```
